### ISSUE TITLE
Error when saving the user profile data

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#40]
<img width="1622" alt="Screenshot 2022-01-18 at 8 14 27 PM" src="https://user-images.githubusercontent.com/4612921/149994892-1929c62c-a579-4d2b-835a-45fd8219c70b.png">

**Comment by nursoltan-s** [comment]
@ThomasKranitsas this is fixed on latest commit.

**Comment by ThomasKranitsas** [comment]
@nursoltan-s which commit? Which branch? Can you please raise a PR against `develop`? I still see the same error

**Comment by nursoltan-s** [comment]
@ThomasKranitsas 
https://github.com/topcoder-platform/micro-frontends-navbar-app/commit/58282b52429af065785d888813f4f9e9a526d9f8

**Comment by ThomasKranitsas** [comment]
Oh, I was using local.topcoder-dev.com :) Thanks!
